### ISSUE TITLE
NPC's

### ISSUE THREAD

**Issue by elijah-h-lgtm** [kurt-stolle/exclrp#1]
NPC's aren't spawning with my own way also they're throwing out errors when I manually spawn them.

**Comment by khwstolle** [comment]
Would you provide me with some errors or code?

**Comment by elijah-h-lgtm** [comment]
It's only since I have ULX installed as I found out. But I couldn't find anywhere in your code to spawn the NPC's.

**Comment by khwstolle** [comment]
I would recommend simply spawning them with the Q-menu, and then making them persistent in the map using the content menu (right click NPC with mouse while holding C).
