### ISSUE TITLE
ExcelRP Gamemode

### ISSUE THREAD

**Issue by Disasty** [kurt-stolle/exclrp#2]
Hey there! I'm having some SQL issues when trying to boot up your gamemode.
Out of curiosity, because I know it's quite old. Does the gamemode still function?

**Comment by khwstolle** [comment]
Hi @Disasty,

I am afraid that I do not know whether this gamemode would still work. It has not been updated in many years. In any case, this is a barebones version that already requires significant effort in terms of adding plugins and other additional functionalities (many are not included here) to make it similar to the version hosted around 2012. On top of that, the scripting API for Garry's Mod has likely evolved, requiring fixes to address potential breaking changes.

I am going to archive this repository. Should you want to pick up fixing the codebase, then I could provide some limited technical support or advice via direct messages.
